POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Dave",
  "email": "dave@example.com",
  "password": "y@ppy&H@ppy",
  "password_confirmation": "y@ppy&H@ppy"
}

###

POST http://localhost:3000/dogs.json
Content-Type: application/json

{
  "name": "Spot",
  "age": 4,
  "breed": "dalmatian"
}